Repository ECP-copa/Cabana, pull requests merged in 2022-04, with the labels that each got.

#464 Update GlobalGrid and Partitioner
  cajita/src/Cajita_GlobalGrid_impl.hpp
  cajita/src/Cajita_Partitioner.hpp
  cajita/src/Cajita_SparseDimPartitioner.hpp
  cajita/unit_test/CMakeLists.txt
  cajita/unit_test/tstGlobalGrid.hpp
  cajita/unit_test/tstPartitioner.hpp
  cajita/unit_test/tstSparseDimPartitioner.hpp
Labels: enhancement

#520 Fixup reference solver example
  example/cajita_tutorial/11_structured_solver/structured_solver_example.cpp
Labels: bug

#517 update sparse paritioner
  cajita/src/Cajita_SparseDimPartitioner.hpp
  cajita/unit_test/tstSparseDimPartitioner.hpp
Labels: bug, enhancement

#522 add halo benchmark
  benchmark/cajita/CMakeLists.txt
  benchmark/cajita/Cajita_HaloPerformance.cpp
Labels: performance
